version: '3.9'
services:
  evo:
    container_name: evo-manage
    image: evo:1.0.0
    build: .
    ports:
      - '${API_PORT}:3000'
    environment:
      - DB_TYPE=${DB_TYPE}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DB=${PG_DB}
      - PG_PORT=${PG_PORT}
      - PG_HOST=${PG_HOST}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
    depends_on:
      - evo-database
    volumes:
      - .:/app
    command: npm run start:prod
    networks:
      - evo_network

  evo-database:
    container_name: evo-database
    image: postgres:12
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - '${PG_PORT}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - evo_network

volumes:
  pgdata: {}

networks:
  evo_network:
    driver: bridge
